# Generated by Django 5.2.1 on 2025-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=50)),
                ('diem', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matkhau', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
